// user actions
export const USER_LOGIN = 'LOGIN';
export const USER_LOGOUT = 'LOGOUT';
export const UPDATE_USERS = 'UPDATE_USERS';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';

// patient actions
export const UPDATE_PATIENTS = 'UPDATE_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const UPDATE_PATIENT_DETAILS = 'UPDATE_PATIENT_DETAILS';
export const EDIT_PATIENT_DETAILS = 'EDIT_PATIENT_DETAILS';

// pregnancy actions
export const UPDATE_PATIENT_PREGNANCY_DETAILS = 'UPDATE_PATIENT_PREGNANCY_DETAILS';
export const UPDATE_MEDICAL_EXAMINATIONS_FOR_PREGNANCY = 'UPDATE_MEDICAL_EXAMINATIONS_FOR_PREGNANCY';

export const UPDATE_MEDICAL_EXAMINATION_DETAILS = 'UPDATE_MEDICAL_EXAMINATION_DETAILS';

// risk actions
export const GENERATE_PDF = 'GENERATE_PDF';
export const UPDATE_PREGNANCY_DATA_FOR_REPORT = 'UPDATE_PREGNANCY_DATA_FOR_REPORT';

// statistics actions
export const UPDATE_MEDIANS_FOR_CHARACTERISTIC = 'UPDATE_MEDIANS_FOR_CHARACTERISTIC';
