// user actions
export const USER_LOGIN = 'LOGIN';
export const USER_LOGOUT = 'LOGOUT';
export const FETCH_USERS = 'FETCH_USERS';
export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const DELETE_USER = 'DELETE_USER';

// patient actions
export const FETCH_PATIENTS = 'FETCH_PATIENTS';
export const ADD_PATIENT = 'ADD_PATIENT';
export const EDIT_PATIENT = 'EDIT_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';

export const FETCH_PATIENT_DETAILS = 'FETCH_PATIENT_DETAILS';
export const EDIT_PATIENT_DETAILS = 'EDIT_PATIENT_DETAILS';

// pregnancy actions
export const FETCH_PATIENT_PREGNANCY_DETAILS = 'FETCH_PATIENT_PREGNANCY_DETAILS';
export const FETCH_MEDICAL_EXAMINATIONS_FOR_PREGNANCY = 'FETCH_MEDICAL_EXAMINATIONS_FOR_PREGNANCY';

export const UPDATE_MEASURES = 'UPDATE_MEASURES';

// risk actions
export const GENERATE_PDF = 'GENERATE_PDF';
export const FETCH_PREGNANCY_DATA_FOR_REPORT = 'FETCH_PREGNANCY_DATA_FOR_REPORT';

// statistics actions
export const FETCH_MEDIANS_FOR_CHARACTERISTIC = 'FETCH_MEDIANS_FOR_CHARACTERISTIC';
