// patients
export const ADD_PATIENT_FORM = 'ADD_PATIENT_FORM';
export const EDIT_PATIENT_FORM = 'EDIT_PATIENT_FORM';

// measurements
export const EDIT_MEDICAL_HISTORY_FORM = 'EDIT_MEDICAL_HISTORY_FORM';
export const EDIT_MATERNAL_CHARACTERISTICS_FORM = 'EDIT_MATERNAL_CHARACTERISTICS_FORM';

// users
export const ADD_USER_FORM = 'ADD_USER_FORM';
export const EDIT_USER_FORM = 'EDIT_USER_FORM';

export const EDIT_USER_PASSWORD_FORM = 'EDIT_USER_PASSWORD_FORM';

// auth
export const LOGIN_FORM = 'LOGIN_FORM';
