// patients
export const ADD_PATIENT_FORM = 'ADD_PATIENT_FORM';
export const EDIT_PATIENT_FORM = 'EDIT_PATIENT_FORM';

// measurements
export const EDIT_FIRST_TRIMESTER_BASIC_INFO_FORM = 'EDIT_FIRST_TRIMESTER_BASIC_INFO_FORM';
export const EDIT_MEDICAL_HISTORY_FORM = 'EDIT_MEDICAL_HISTORY_FORM';
export const EDIT_MATERNAL_CHARACTERISTICS_FORM = 'EDIT_MATERNAL_CHARACTERISTICS_FORM';
export const EDIT_BIOPHYSICAL_MEASUREMENTS_FORM = 'EDIT_BIOPHYSICAL_MEASUREMENTS_FORM';
export const EDIT_BIOCHEMICAL_MEASUREMENTS_FORM = 'EDIT_BIOCHEMICAL_MEASUREMENTS_FORM';

// users
export const ADD_USER_FORM = 'ADD_USER_FORM';
export const EDIT_USER_FORM = 'EDIT_USER_FORM';

export const EDIT_USER_PASSWORD_FORM = 'EDIT_USER_PASSWORD_FORM';

// auth
export const LOGIN_FORM = 'LOGIN_FORM';
